"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { Brand } from "@prisma/client";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { ArrowLeft, Wand2 } from "lucide-react";
import Link from "next/link";

// Helper component for displaying a single DNA item
const DnaItem = ({ label, value }: { label: string; value: string | string[] | null | undefined }) => {
  if (!value) return null;
  const displayValue = Array.isArray(value) ? value.join(", ") : value;
  return (
    <div>
      <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">{label}</h3>
      <p className="text-brand-silver mt-1">{displayValue}</p>
    </div>
  );
};

// Main component for the Brand DNA section
const BrandDnaSection = ({ brand, onGenerate, isLoading }: { brand: Brand; onGenerate: () => void; isLoading: boolean; }) => {
  const hasDna = brand.mission || brand.vision;

  return (
    <Card className="bg-brand-slate/50 border-slate-800">
      <CardHeader>
        <CardTitle className="text-brand-silver">Brand DNA</CardTitle>
        <CardDescription className="text-slate-400">
          The core strategic foundation of your brand, generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {hasDna ? (
          <div className="space-y-6">
            <DnaItem label="Mission" value={brand.mission} />
            <DnaItem label="Vision" value={brand.vision} />
            <DnaItem label="Core Values" value={brand.values as string[]} />
            <DnaItem label="Target Audience" value={brand.targetAudience} />
            <DnaItem label="Unique Selling Proposition" value={brand.usp} />
            <DnaItem label="Personality Traits" value={brand.personalityTraits as string[]} />
          </div>
        ) : (
          <div className="text-center py-10">
            <p className="text-slate-400 mb-6">Your Brand DNA hasn't been generated yet.</p>
            <Button onClick={onGenerate} disabled={isLoading} className="bg-brand-blue hover:bg-blue-700">
              <Wand2 className="mr-2 h-4 w-4" />
              {isLoading ? "Generating..." : "Generate Brand DNA"}
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
};

// Component for the Messaging Matrix
const MessagingMatrixSection = ({ brand, onGenerate, isLoading }: { brand: Brand; onGenerate: () => void; isLoading: boolean; }) => {
  const matrix = brand.messagingMatrix as any;
  const hasDna = brand.mission;

  return (
    <Card className="bg-brand-slate/50 border-slate-800">
      <CardHeader>
        <CardTitle className="text-brand-silver">Messaging Matrix</CardTitle>
        <CardDescription className="text-slate-400">
          Your brand's core messaging, ready to deploy across all channels.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {matrix ? (
          <div className="space-y-6">
            <DnaItem label="Master Tagline" value={matrix.masterTagline} />
            <div>
              <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Elevator Pitch</h3>
              <div className="text-brand-silver mt-1 space-y-2">
                <p><span className="font-semibold">15s:</span> {matrix.elevatorPitch?.p15s}</p>
                <p><span className="font-semibold">30s:</span> {matrix.elevatorPitch?.p30s}</p>
                <p><span className="font-semibold">60s:</span> {matrix.elevatorPitch?.p60s}</p>
              </div>
            </div>
            <DnaItem label="Boilerplate" value={matrix.boilerplate} />
             <div>
              <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Benefit Stack</h3>
              <ul className="list-disc list-inside mt-1 space-y-1 text-brand-silver">
                {matrix.benefitStack?.map((item: any, i: number) => <li key={i}><strong>{item.title}:</strong> {item.description}</li>)}
              </ul>
            </div>
            <DnaItem label="Narrative Themes" value={matrix.narrativeThemes} />
             <div>
              <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Say / Don't Say</h3>
              <div className="grid grid-cols-2 gap-4 mt-1">
                <div>
                  <h4 className="text-green-400 font-semibold">Say</h4>
                  <ul className="list-disc list-inside text-brand-silver">{matrix.sayDontSay?.say.map((s: string, i: number) => <li key={i}>{s}</li>)}</ul>
                </div>
                 <div>
                  <h4 className="text-red-400 font-semibold">Don't Say</h4>
                  <ul className="list-disc list-inside text-brand-silver">{matrix.sayDontSay?.dontSay.map((s: string, i: number) => <li key={i}>{s}</li>)}</ul>
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center py-10">
            <p className="text-slate-400 mb-6">Generate your Brand DNA first to unlock the Messaging Matrix.</p>
            <Button onClick={onGenerate} disabled={isLoading || !hasDna} className="bg-brand-blue hover:bg-blue-700 disabled:bg-slate-600 disabled:cursor-not-allowed">
              <Wand2 className="mr-2 h-4 w-4" />
              {isLoading ? "Generating..." : "Generate Messaging Matrix"}
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// Component for Content Pillars
const ContentPillarsSection = ({ brand, onGenerate, isLoading }: { brand: Brand; onGenerate: () => void; isLoading: boolean; }) => {
    const pillars = brand.contentPillars as any[];
    const hasDna = brand.mission;

    return (
        <Card className="bg-brand-slate/50 border-slate-800">
            <CardHeader>
                <CardTitle className="text-brand-silver">Content Pillars</CardTitle>
                <CardDescription className="text-slate-400">
                    The strategic themes that guide your content creation.
                </CardDescription>
            </CardHeader>
            <CardContent>
                {pillars ? (
                    <div className="grid md:grid-cols-2 gap-6">
                        {pillars.map((pillar, i) => (
                            <div key={i} className="bg-slate-900/50 p-4 rounded-lg">
                                <h4 className="font-semibold text-brand-blue">{pillar.title}</h4>
                                <p className="text-sm text-slate-300 mt-1 mb-3">{pillar.description}</p>
                                <h5 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Example Topics:</h5>
                                <ul className="list-disc list-inside text-sm text-slate-300 mt-1 space-y-1">
                                    {pillar.topics.map((topic: string, j: number) => <li key={j}>{topic}</li>)}
                                </ul>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="text-center py-10">
                        <p className="text-slate-400 mb-6">Generate your Brand DNA first to unlock Content Pillars.</p>
                        <Button onClick={onGenerate} disabled={isLoading || !hasDna} className="bg-brand-blue hover:bg-blue-700 disabled:bg-slate-600 disabled:cursor-not-allowed">
                            <Wand2 className="mr-2 h-4 w-4" />
                            {isLoading ? "Generating..." : "Generate Content Pillars"}
                        </Button>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}

// New component for Post Ideas
const PostIdeasSection = ({ brand, onGenerate, isLoading }: { brand: Brand; onGenerate: () => void; isLoading: boolean; }) => {
    const ideas = brand.postIdeas as any[];
    const hasPillars = brand.contentPillars;

    return (
        <Card className="bg-brand-slate/50 border-slate-800">
            <CardHeader>
                <CardTitle className="text-brand-silver">Social Post Ideas</CardTitle>
                <CardDescription className="text-slate-400">
                    A list of ready-to-use ideas for your social media channels, based on your content pillars.
                </CardDescription>
            </CardHeader>
            <CardContent>
                {ideas ? (
                    <div className="space-y-4">
                        {ideas.map((idea, i) => (
                            <div key={i} className="bg-slate-900/50 p-4 rounded-lg border border-slate-800">
                                <p className="text-xs font-semibold text-brand-blue uppercase tracking-wider">{idea.format} - ({idea.pillar})</p>
                                <h4 className="font-semibold text-brand-silver mt-2">"{idea.hook}"</h4>
                                <p className="text-sm text-slate-300 mt-1">{idea.body}</p>
                                <p className="text-sm text-slate-400 mt-2 italic">CTA: {idea.cta}</p>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="text-center py-10">
                        <p className="text-slate-400 mb-6">Generate your Content Pillars first to unlock Post Ideas.</p>
                        <Button onClick={onGenerate} disabled={isLoading || !hasPillars} className="bg-brand-blue hover:bg-blue-700 disabled:bg-slate-600 disabled:cursor-not-allowed">
                            <Wand2 className="mr-2 h-4 w-4" />
                            {isLoading ? "Generating..." : "Generate Post Ideas"}
                        </Button>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}


export default function BrandPage() {
  const [brand, setBrand] = useState<Brand | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingDna, setIsGeneratingDna] = useState(false);
  const [isGeneratingMatrix, setIsGeneratingMatrix] = useState(false);
  const [isGeneratingPillars, setIsGeneratingPillars] = useState(false);
  const [isGeneratingIdeas, setIsGeneratingIdeas] = useState(false);
  const params = useParams();
  const router = useRouter();
  const id = params.id as string;

  const fetchBrand = async () => {
    if (!id) return;
    try {
      const response = await fetch(`/api/brands/${id}`);
      if (!response.ok) throw new Error("Brand not found");
      const data = await response.json();
      setBrand(data);
    } catch (error) {
      console.error(error);
      router.push("/dashboard");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    setIsLoading(true);
    fetchBrand();
  }, [id]);

  const handleGenerateDna = async () => {
    setIsGeneratingDna(true);
    try {
      await fetch('/api/generate/brand-discovery', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brandId: id }),
      });
      await fetchBrand();
    } catch (error) { console.error(error); }
    finally { setIsGeneratingDna(false); }
  };

  const handleGenerateMatrix = async () => {
    setIsGeneratingMatrix(true);
    try {
      await fetch('/api/generate/messaging-matrix', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brandId: id }),
      });
      await fetchBrand();
    } catch (error) { console.error(error); }
    finally { setIsGeneratingMatrix(false); }
  };

  const handleGeneratePillars = async () => {
    setIsGeneratingPillars(true);
    try {
      await fetch('/api/generate/content-pillars', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brandId: id }),
      });
      await fetchBrand();
    } catch (error) { console.error(error); }
    finally { setIsGeneratingPillars(false); }
  };

  const handleGenerateIdeas = async () => {
    setIsGeneratingIdeas(true);
    try {
      await fetch('/api/generate/post-ideas', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ brandId: id }),
      });
      await fetchBrand();
    } catch (error) { console.error(error); }
    finally { setIsGeneratingIdeas(false); }
  };

  if (isLoading) {
    return <div className="text-center text-slate-400">Loading Brand...</div>;
  }

  if (!brand) {
    return null;
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-8"
    >
      <div className="mb-8">
        <Link href="/dashboard" className="flex items-center gap-2 text-slate-400 hover:text-brand-silver transition-colors">
          <ArrowLeft size={16} />
          Back to Dashboard
        </Link>
      </div>

      <header>
        <h1 className="text-4xl font-bold text-brand-silver">{brand.name}</h1>
        {brand.description && <p className="text-slate-400 mt-2 max-w-2xl">{brand.description}</p>}
      </header>

      <BrandDnaSection brand={brand} onGenerate={handleGenerateDna} isLoading={isGeneratingDna} />
      <MessagingMatrixSection brand={brand} onGenerate={handleGenerateMatrix} isLoading={isGeneratingMatrix} />
      <ContentPillarsSection brand={brand} onGenerate={handleGeneratePillars} isLoading={isGeneratingPillars} />
      <PostIdeasSection brand={brand} onGenerate={handleGenerateIdeas} isLoading={isGeneratingIdeas} />

    </motion.div>
  );
}